### ISSUE TITLE
Gitlab repo is not available

### ISSUE THREAD

**Issue by xymeng16** [OnePlus-11-Development/android#1]
https://gitlab.com/oneplus-11-development/ seems not publicly available anymore, hence `vendor_oneplus_salami` and  `vendor_oneplus_sm8550-common` are not able to be synced.

**Comment by E1hanH** [comment]
comment out the sync and follow the instructions https://github.com/OnePlus-11-Development/android#obtaining-the-proprietary-files seems to work

also, you might need to --force-sync to take care of the selinux stuff

**Comment by bgcngm** [comment]
> https://gitlab.com/oneplus-11-development/ seems not publicly available anymore, hence `vendor_oneplus_salami` and `vendor_oneplus_sm8550-common` are not able to be synced.

It has been made public.
